{% set name = "mistral-inference" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mistral_inference-{{ version }}.tar.gz
  sha256: 838ef36cdb8f0fe970df1f9e5d270d8c174081eaa9acda77534b187e27b0d5b3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytorch
    - setuptools
    - setuptools_scm
    - poetry
  run:
    - python >={{ python_min }}
    - fire
    - mistral-common
    - pillow
    - pytorch
    - safetensors
    - simple-parsing
    - xformers

test:
  imports:
    - mistral_inference
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mistralai/mistral-inference
  summary: Official inference library for Mistral models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
