{% set name = "mistral-inference" %}
{% set version = "1.4.0" %}
{% set python_min = python_min|default("3.8") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mistral_inference-{{ version }}.tar.gz
  sha256: c3614d6eaf9b2c059cd6cb6e1462f65ac8f0bab8540fa241670d020fc70ad469

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytorch
    - setuptools
    - setuptools_scm
    - poetry
  run:
    - python >={{ python_min }}
    - fire
    - mistral-common
    - pillow
    - pytorch
    - safetensors
    - simple-parsing
    - xformers

test:
  imports:
    - mistral_inference
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mistralai/mistral-inference
  summary: Official inference library for Mistral models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
